'use client';

import { useMemo, useState } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import remarkMath from 'remark-math';
import rehypeKatex from 'rehype-katex';
import {
  BookOpen,
  Check,
  ChevronDown,
  ChevronUp,
  Copy,
  Download,
  FileText,
  Lightbulb,
  Printer,
} from 'lucide-react';

interface NotesPanelProps {
  notes: string;
  keyPoints: string[];
  lessonTitle: string;
}

function escapeHtml(input: string) {
  return input
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#039;');
}

function safeFilename(input: string) {
  return input
    .trim()
    .toLowerCase()
    .replaceAll(/[^a-z0-9]+/g, '-')
    .replaceAll(/-+/g, '-')
    .replaceAll(/(^-|-$)/g, '')
    .slice(0, 80);
}

export default function NotesPanel({ notes, keyPoints, lessonTitle }: NotesPanelProps) {
  const [expandedSections, setExpandedSections] = useState<string[]>(['keyPoints', 'notes']);
  const [downloading, setDownloading] = useState(false);
  const [copied, setCopied] = useState(false);

  const markdownPlugins = useMemo(() => [remarkGfm, remarkMath], []);
  const htmlPlugins = useMemo(() => [rehypeKatex], []);

  const toggleSection = (section: string) => {
    setExpandedSections(prev =>
      prev.includes(section) ? prev.filter(s => s !== section) : [...prev, section]
    );
  };

  const handleDownload = async (format: 'md' | 'print') => {
    setDownloading(true);

    try {
      if (format === 'print') {
        const title = escapeHtml(`${lessonTitle} — Study Notes`);
        const points = keyPoints.map(escapeHtml);
        const bodyNotes = escapeHtml(notes).replaceAll('\n', '<br/>');

        const printContent = `
<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>${title}</title>
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap');
      * { box-sizing: border-box; }
      body {
        font-family: 'Inter', ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif;
        padding: 32px;
        max-width: 900px;
        margin: 0 auto;
        color: #111827;
        line-height: 1.65;
      }
      h1 { font-size: 22px; margin: 0 0 16px; }
      h2 { font-size: 16px; margin: 24px 0 12px; }
      .card { border: 1px solid #e5e7eb; border-radius: 12px; padding: 16px; }
      ul { margin: 0; padding-left: 18px; }
      li { margin: 8px 0; }
      .notes { white-space: normal; }
      .footer { margin-top: 28px; padding-top: 12px; border-top: 1px solid #e5e7eb; font-size: 12px; color: #6b7280; }
      @media print { body { padding: 18px; } }
    </style>
  </head>
  <body>
    <h1>${escapeHtml(lessonTitle)}</h1>

    <div class="card">
      <h2>Key Points</h2>
      <ul>
        ${points.map(p => `<li>${p}</li>`).join('')}
      </ul>
    </div>

    <h2>Detailed Notes</h2>
    <div class="card notes">${bodyNotes}</div>

    <div class="footer">Generated by Agentic Learning</div>
  </body>
</html>
        `;

        const printWindow = window.open('', '_blank');
        if (printWindow) {
          printWindow.document.write(printContent);
          printWindow.document.close();
          printWindow.focus();
          printWindow.print();
        }
      } else {
        const content = `# ${lessonTitle}

## Key Points
${keyPoints.map(p => `- ${p}`).join('\n')}

---

## Detailed Notes
${notes}
`;

        const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${safeFilename(lessonTitle) || 'study-notes'}.md`;
        a.click();
        URL.revokeObjectURL(url);
      }
    } finally {
      setDownloading(false);
    }
  };

  const handleCopy = () => {
    const content = `${lessonTitle}\n\nKey Points:\n${keyPoints.map(p => `• ${p}`).join('\n')}\n\nNotes:\n${notes}`;
    navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="bg-white dark:bg-gray-900 rounded-2xl border border-gray-200 dark:border-gray-800 overflow-hidden">
      <div className="p-4 border-b border-gray-200 dark:border-gray-800 flex items-center justify-between bg-gradient-to-r from-blue-50 to-white dark:from-gray-950 dark:to-gray-900">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 bg-blue-600 rounded-xl flex items-center justify-center">
            <BookOpen className="w-5 h-5 text-white" />
          </div>
          <div>
            <h2 className="text-lg font-bold text-gray-900 dark:text-gray-100">Study Notes</h2>
            <p className="text-xs text-gray-500 dark:text-gray-400">Comprehensive learning material</p>
          </div>
        </div>
        <div className="flex gap-2">
          <button
            onClick={handleCopy}
            className="flex items-center gap-2 px-3 py-2 bg-gray-100 dark:bg-gray-800 hover:bg-gray-200 dark:hover:bg-gray-700 text-gray-700 dark:text-gray-200 rounded-lg text-sm font-medium transition-colors"
            title="Copy to clipboard"
          >
            {copied ? <Check className="w-4 h-4 text-green-600" /> : <Copy className="w-4 h-4" />}
          </button>
          <button
            onClick={() => handleDownload('print')}
            className="flex items-center gap-2 px-3 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg text-sm font-medium transition-colors"
          >
            <Printer className="w-4 h-4" />
            Print / PDF
          </button>
          <button
            onClick={() => handleDownload('md')}
            disabled={downloading}
            className="flex items-center gap-2 px-3 py-2 bg-gray-900 hover:bg-gray-800 disabled:opacity-60 text-white rounded-lg text-sm font-medium transition-colors"
          >
            <Download className="w-4 h-4" />
            {downloading ? '...' : 'Export'}
          </button>
        </div>
      </div>

      <div>
        <div className="border-b border-gray-200 dark:border-gray-800">
          <button
            onClick={() => toggleSection('keyPoints')}
            className="w-full p-4 flex items-center justify-between hover:bg-yellow-50 dark:hover:bg-yellow-950/20 transition-colors"
          >
            <div className="flex items-center gap-3">
              <div className="w-8 h-8 bg-yellow-100 dark:bg-yellow-950/40 rounded-lg flex items-center justify-center">
                <Lightbulb className="w-4 h-4 text-yellow-600" />
              </div>
              <div className="text-left">
                <span className="font-semibold text-gray-900 dark:text-gray-100">Key Points</span>
                <p className="text-xs text-gray-500 dark:text-gray-400">{keyPoints.length} important concepts</p>
              </div>
            </div>
            {expandedSections.includes('keyPoints') ? (
              <ChevronUp className="w-5 h-5 text-gray-400" />
            ) : (
              <ChevronDown className="w-5 h-5 text-gray-400" />
            )}
          </button>

          {expandedSections.includes('keyPoints') && (
            <div className="px-4 pb-4 bg-yellow-50/50 dark:bg-yellow-950/10">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
                {keyPoints.map((point, idx) => (
                  <div
                    key={idx}
                    className="flex items-start gap-3 bg-white dark:bg-gray-900 p-3 rounded-lg border border-yellow-200 dark:border-yellow-900/40"
                  >
                    <span className="w-6 h-6 bg-yellow-100 dark:bg-yellow-950/40 rounded-full flex items-center justify-center text-xs font-bold text-yellow-700 flex-shrink-0">
                      {idx + 1}
                    </span>
                    <span className="text-gray-800 dark:text-gray-200 text-sm font-medium">{point}</span>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>

        <div className="border-b border-gray-200 dark:border-gray-800">
          <button
            onClick={() => toggleSection('notes')}
            className="w-full p-4 flex items-center justify-between hover:bg-blue-50 dark:hover:bg-blue-950/20 transition-colors"
          >
            <div className="flex items-center gap-3">
              <div className="w-8 h-8 bg-blue-100 dark:bg-blue-950/40 rounded-lg flex items-center justify-center">
                <FileText className="w-4 h-4 text-blue-600" />
              </div>
              <div className="text-left">
                <span className="font-semibold text-gray-900 dark:text-gray-100">Detailed Notes</span>
                <p className="text-xs text-gray-500 dark:text-gray-400">In-depth explanations and examples</p>
              </div>
            </div>
            {expandedSections.includes('notes') ? (
              <ChevronUp className="w-5 h-5 text-gray-400" />
            ) : (
              <ChevronDown className="w-5 h-5 text-gray-400" />
            )}
          </button>

          {expandedSections.includes('notes') && (
            <div className="px-4 pb-4 bg-white dark:bg-gray-900">
              <div className="bg-gray-50 dark:bg-gray-950 rounded-xl p-6 border border-gray-200 dark:border-gray-800">
                <div className="prose prose-gray max-w-none dark:prose-invert prose-sm sm:prose-base">
                  <ReactMarkdown
                    remarkPlugins={markdownPlugins}
                    rehypePlugins={htmlPlugins}
                    components={{
                      p: ({ children }) => (
                        <p className="mb-4 leading-relaxed text-gray-700 dark:text-gray-300">{children}</p>
                      ),
                      h1: ({ children }) => (
                        <h1 className="text-2xl font-bold text-gray-900 dark:text-white mb-4 mt-6">{children}</h1>
                      ),
                      h2: ({ children }) => (
                        <h2 className="text-xl font-bold text-gray-900 dark:text-white mb-3 mt-5">{children}</h2>
                      ),
                      h3: ({ children }) => (
                        <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-2 mt-4">{children}</h3>
                      ),
                      ul: ({ children }) => (
                        <ul className="list-disc pl-6 mb-4 space-y-2 text-gray-700 dark:text-gray-300">{children}</ul>
                      ),
                      ol: ({ children }) => (
                        <ol className="list-decimal pl-6 mb-4 space-y-2 text-gray-700 dark:text-gray-300">{children}</ol>
                      ),
                      li: ({ children }) => (
                        <li className="leading-relaxed">{children}</li>
                      ),
                      code: ({ className, children, ...props }) => {
                        const match = /language-(\w+)/.exec(className || '');
                        const isInline = !match;
                        return isInline ? (
                          <code className="px-1.5 py-0.5 bg-gray-200 dark:bg-gray-800 rounded text-sm font-mono text-purple-600 dark:text-purple-400" {...props}>
                            {children}
                          </code>
                        ) : (
                          <code className={className} {...props}>
                            {children}
                          </code>
                        );
                      },
                      pre: ({ children }) => (
                        <pre className="bg-gray-900 text-gray-100 p-4 rounded-xl overflow-x-auto mb-4 text-sm">
                          {children}
                        </pre>
                      ),
                      a({ href, children, ...props }) {
                        const safeHref =
                          href && (href.startsWith('https://') || href.startsWith('http://') || href.startsWith('mailto:'))
                              ? href
                              : undefined;
                        if (!safeHref) return <span {...props}>{children}</span>;
                        return (
                          <a href={safeHref} target="_blank" rel="noreferrer noopener" className="text-blue-600 dark:text-blue-400 hover:underline" {...props}>
                            {children}
                          </a>
                        );
                      },
                      blockquote: ({ children }) => (
                        <blockquote className="border-l-4 border-blue-500 pl-4 py-2 my-4 bg-blue-50 dark:bg-blue-950/30 rounded-r-lg italic text-gray-700 dark:text-gray-300">
                          {children}
                        </blockquote>
                      ),
                      table: ({ children }) => (
                        <div className="overflow-x-auto my-4">
                          <table className="min-w-full divide-y divide-gray-200 dark:divide-gray-700 border border-gray-200 dark:border-gray-700 rounded-lg">
                            {children}
                          </table>
                        </div>
                      ),
                      thead: ({ children }) => (
                        <thead className="bg-gray-100 dark:bg-gray-800">{children}</thead>
                      ),
                      td: ({ children }) => (
                        <td className="px-4 py-2 text-gray-700 dark:text-gray-300">{children}</td>
                      ),
                    }}
                  >
                    {notes}
                  </ReactMarkdown>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

